openapi: 3.0.0
info:
  title: Family Marketplace and Legacy Fund API
  description: API documentation for the Family Project including Users, Products, Family History, Donations, and Applications.
  version: 1.0.0

servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /users:
    get:
      summary: Get all users
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /products:
    get:
      summary: Get all products
      tags:
        - Products
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

  /family-history:
    get:
      summary: Get all family history records
      tags:
        - FamilyHistory
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of family members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FamilyHistory"

  /donations:
    get:
      summary: Get all donations
      tags:
        - Donations
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of donations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Donation"

  /donation-application:
    get:
      summary: Get all donation applications
      tags:
        - DonationApplications
      security:
        - bearerAuth: []
      responses:
        "200":
          description: A list of donation applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DonationApplication"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      required:
        - name
        - email
        - age
        - password
      properties:
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        password:
          type: string
        role:
          type: string
          enum: [admin, user]
        permissions:
          type: array
          items:
            type: string

    Product:
      type: object
      required:
        - title
        - category
        - price
        - description
      properties:
        title:
          type: string
        category:
          type: string
        price:
          type: number
        description:
          type: string
        imageUrl:
          type: string
        addedBy:
          type: string
          format: uuid

    FamilyHistory:
      type: object
      required:
        - name
        - gender
        - dateOfBirth
        - relation
        - status
      properties:
        name:
          type: string
        gender:
          type: string
          enum: [male, female, other]
        dateOfBirth:
          type: string
          format: date
        dateOfDeath:
          type: string
          format: date
        relation:
          type: string
        bio:
          type: string
        image:
          type: string
        status:
          type: string
          enum: [alive, death]
        parent:
          type: string
          format: uuid

    Donation:
      type: object
      required:
        - donor
        - phone
        - address
        - amount
      properties:
        donor:
          type: string
          format: uuid
        phone:
          type: string
        address:
          type: string
        amount:
          type: number
        message:
          type: string

    DonationApplication:
      type: object
      required:
        - applicant
        - phoneNumber
        - address
        - purpose
        - description
      properties:
        applicant:
          type: string
          format: uuid
        phoneNumber:
          type: string
        address:
          type: string
        purpose:
          type: string
        description:
          type: string
        amountRequested:
          type: number
        status:
          type: string
          enum: [pending, approved, rejected]
